apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: backend

data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    protected-mode yes

    requirepass ${REDIS_PASSWORD}
    masterauth ${REDIS_PASSWORD}

    appendonly yes
    appendfsync everysec

    save 900 1
    save 300 10
    save 60 10000

    repl-diskless-sync yes
    repl-diskless-sync-delay 5

    repl-timeout 60
    repl-ping-replica-period 10

    maxmemory-policy allkeys-lru
    loglevel notice

  sentinel.conf: |
    sentinel resolve-hostnames yes
    sentinel announce-hostnames yes

    bind 0.0.0.0
    port 26379
    protected-mode no

    sentinel monitor mymaster redis-primary 6379 2
    sentinel auth-pass mymaster ${REDIS_PASSWORD}

    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 60000
    sentinel parallel-syncs mymaster 1

    loglevel notice