"""create polygon_mappings table

Revision ID: 8b53d64cb79d
Revises: e6e367e9ad33
Create Date: 2026-09-07 15:15:23.338753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b53d64cb79d'
down_revision: Union[str, Sequence[str], None] = 'e6e367e9ad33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polygon_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('api_ticker', sa.String(length=100), nullable=False),
    sa.Column('ws_ticker', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_ticker'),
    sa.UniqueConstraint('symbol_id'),
    sa.UniqueConstraint('ws_ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('polygon_mappings')
    # ### end Alembic commands ###
