"""create binance_mapping table

Revision ID: e6e367e9ad33
Revises: f77d65aee70a
Create Date: 2026-08-19 11:41:45.930080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6e367e9ad33'
down_revision: Union[str, Sequence[str], None] = 'f77d65aee70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binance_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id'),
    sa.UniqueConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('binance_mappings')
    # ### end Alembic commands ###
