apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-trading-backend-config
  namespace: backend
data:
  DEBUG: "false"
  REDIS_SENTINEL_HOSTS: "redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379"
  REDIS_SENTINEL_MASTER_NAME: "mymaster"
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_SECONDS: "86400"
  JWT_REFRESH_TOKEN_EXPIRE_SECONDS: "604800"