apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrations
  namespace: backend

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: migrations
          image: ghcr.io/sayfullaev1999/crypto-trading-backend:IMAGE_TAG

          command:
            - alembic
            - -c
            - src/alembic.ini
            - upgrade
            - head

          env:
            - name: POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: POSTGRES_DSN