apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-api
  namespace: backend
spec:
  ingressClassName: traefik

  tls:
    - hosts:
        - crypto.dezz.uz
      secretName: crypto-dezz-uz-tls

  rules:
    - host: crypto.dezz.uz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-api
                port:
                  number: 8000