apiVersion: v1

kind: Service

metadata:
  name: pgbouncer
  namespace: backend
  labels:
    app: pgbouncer

spec:
  selector:
    app: pgbouncer
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP

    - name: metrics
      port: 9127
      targetPort: metrics
      protocol: TCP

  type: ClusterIP