name: Test GCP OIDC

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  test-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/982637213247/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: github-actions-deployer@project-2e6d4ec9-7a27-4123-9db.iam.gserviceaccount.com

      - name: Verify identity
        run: |
          gcloud auth list
          gcloud config get-value project

      - name: Test IAP access
        run: |
          gcloud compute ssh instance-20260904-100901 \
            --zone=europe-west3-c \
            --tunnel-through-iap \
            --command="echo 'GITHUB ACTIONS → IAP → VM: SUCCESS'"